server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qq?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 216216
logging:
  path: C:/Users/18368/Desktop/log
  file: spider
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
 
      